In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("weightLogInfo_merged.csv")

# Quick Overview

In [3]:
df.head()

,Id,Date,WeightKg,WeightPounds,Fat,BMI,IsManualReport,LogId
0,1503960366,05/02/2016 11:59:59 PM,52.6,115.96,22.0,22.65,True,1.462230e+12
1,1503960366,05/03/2016 11:59:59 PM,52.6,115.96,NaN,22.65,True,1.462320e+12
2,1927972279,4/13/2016 1:08:52 AM,133.5,294.32,NaN,47.54,False,1.460510e+12
3,2873212765,4/21/2016 11:59:59 PM,56.7,125.00,NaN,21.45,True,1.461280e+12
4,2873212765,05/12/2016 11:59:59 PM,57.3,126.32,NaN,21.69,True,1.463100e+12

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 67 entries, 0 to 66
Data columns (total 8 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Id              67 non-null     int64
 1   Date            67 non-null     object
 2   WeightKg        67 non-null     float64
 3   WeightPounds    67 non-null     float64
 4   Fat             2 non-null      float64
 5   BMI             67 non-null     float64
 6   IsManualReport  67 non-null     bool
 7   LogId           67 non-null     float64
dtypes: bool(1), float64(5), int64(1), object(1)
memory usage: 3.9+ KB

In [5]:
df.dtypes

Id                  int64
Date               object
WeightKg          float64
WeightPounds      float64
Fat               float64
BMI               float64
IsManualReport       bool
LogId             float64
dtype: object

In [6]:
# Check missing values

df.isnull().sum()

Id                 0
Date               0
WeightKg           0
WeightPounds       0
Fat               65
BMI                0
IsManualReport     0
LogId              0
dtype: int64

### We can see that Fat has null values but For this project we can keep them because body fat is optional in Fitbit data.

# Why Fat has null values?

In fitness trackers (Fitbit/Strava type data):

Weight and BMI are recorded automatically or frequently.

Body Fat % is recorded only if the user manually enters it or uses a smart scale.

So many users did not log body fat, which creates null values.

In [7]:
# check duplicate records

df.duplicated().sum()

0

In [9]:
df["Date"] # need to convert the date column into datetime

0     05/02/2016 11:59:59 PM
1     05/03/2016 11:59:59 PM
2       4/13/2016 1:08:52 AM
3      4/21/2016 11:59:59 PM
4     05/12/2016 11:59:59 PM
               ...
62    05/06/2016 06:43:35 AM
63    05/08/2016 07:35:53 AM
64    05/09/2016 06:39:44 AM
65    05/11/2016 06:51:47 AM
66    05/12/2016 06:42:53 AM
Name: Date, Length: 67, dtype: object

## Convert Date Column

In [10]:
df['Date'] = pd.to_datetime(df['Date'], format='mixed')

In [11]:
df['Date']

0    2016-05-02 23:59:59
1    2016-05-03 23:59:59
2    2016-04-13 01:08:52
3    2016-04-21 23:59:59
4    2016-05-12 23:59:59
             ...
62   2016-05-06 06:43:35
63   2016-05-08 07:35:53
64   2016-05-09 06:39:44
65   2016-05-11 06:51:47
66   2016-05-12 06:42:53
Name: Date, Length: 67, dtype: datetime64[ns]

## Convert to dd/mm/yyyy

In [12]:
df['Date'] = df['Date'].dt.strftime('%d/%m/%Y')

In [13]:
df["Date"].head()

0    02/05/2016
1    03/05/2016
2    13/04/2016
3    21/04/2016
4    12/05/2016
Name: Date, dtype: object

In [14]:
df

,Id,Date,WeightKg,WeightPounds,Fat,BMI,IsManualReport,LogId
0,1503960366,02/05/2016,52.6,115.96,22.0,22.65,True,1.462230e+12
1,1503960366,03/05/2016,52.6,115.96,NaN,22.65,True,1.462320e+12
2,1927972279,13/04/2016,133.5,294.32,NaN,47.54,False,1.460510e+12
3,2873212765,21/04/2016,56.7,125.00,NaN,21.45,True,1.461280e+12
4,2873212765,12/05/2016,57.3,126.32,NaN,21.69,True,1.463100e+12
...,...,...,...,...,...,...,...,...
62,8877689391,06/05/2016,85.0,187.39,NaN,25.44,False,1.462520e+12
63,8877689391,08/05/2016,85.4,188.27,NaN,25.56,False,1.462690e+12
64,8877689391,09/05/2016,85.5,188.50,NaN,25.61,False,1.462780e+12
65,8877689391,11/05/2016,85.4,188.27,NaN,25.56,False,1.462950e+12
66,8877689391,12/05/2016,84.0,185.19,NaN,25.14,False,1.463040e+12

# Save clean dataset

In [15]:
df.to_csv("clean_weightLogInfo.csv", index=False)

# Load the clean dataset

In [16]:
df = pd.read_csv("clean_weightLogInfo.csv")

In [17]:
df.head()

,Id,Date,WeightKg,WeightPounds,Fat,BMI,IsManualReport,LogId
0,1503960366,02/05/2016,52.6,115.96,22.0,22.65,True,1.462230e+12
1,1503960366,03/05/2016,52.6,115.96,NaN,22.65,True,1.462320e+12
2,1927972279,13/04/2016,133.5,294.32,NaN,47.54,False,1.460510e+12
3,2873212765,21/04/2016,56.7,125.00,NaN,21.45,True,1.461280e+12
4,2873212765,12/05/2016,57.3,126.32,NaN,21.69,True,1.463100e+12