In [1]:
# Importing libraries
import pandas as pd
import numpy as np

In [44]:
# Load the dataset

df = pd.read_csv("dailyActivity_merged.csv")

In [45]:
df

,Id,ActivityDate,TotalSteps,TotalDistance,TrackerDistance,LoggedActivitiesDistance,VeryActiveDistance,ModeratelyActiveDistance,LightActiveDistance,SedentaryActiveDistance,VeryActiveMinutes,FairlyActiveMinutes,LightlyActiveMinutes,SedentaryMinutes,Calories
0,1503960366,04/12/2016,13162,8.5,8.5,0.0,1.9,0.6,6.1,0.00,25,13,328,728,1985
1,1503960366,4/13/2016,10735,7.0,7.0,0.0,1.6,0.7,4.7,0.00,21,19,217,776,1797
2,1503960366,4/14/2016,10460,6.7,6.7,0.0,2.4,0.4,3.9,0.00,30,11,181,1218,1776
3,1503960366,4/15/2016,9762,6.3,6.3,0.0,2.1,1.3,2.8,0.00,29,34,209,726,1745
4,1503960366,4/16/2016,12669,8.2,8.2,0.0,2.7,0.4,5.0,0.00,36,10,221,773,1863
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
935,8877689391,05/08/2016,10686,8.1,8.1,0.0,1.1,0.2,6.8,0.00,17,4,245,1174,2847
936,8877689391,05/09/2016,20226,18.3,18.3,0.0,11.1,0.8,6.2,0.05,73,19,217,1131,3710
937,8877689391,05/10/2016,10733,8.1,8.1,0.0,1.4,0.5,6.3,0.00,18,11,224,1187,2832
938,8877689391,05/11/2016,21420,19.6,19.6,0.0,13.2,0.4,5.9,0.00,88,12,213,1127,3832
939,8877689391,05/12/2016,8064,6.1,6.1,0.0,1.8,0.0,4.3,0.00,23,1,137,770,1849

### Quick Overview

In [60]:
# Display first few rows
df.head()

,Id,ActivityDate,TotalSteps,TotalDistance,TrackerDistance,LoggedActivitiesDistance,VeryActiveDistance,ModeratelyActiveDistance,LightActiveDistance,SedentaryActiveDistance,VeryActiveMinutes,FairlyActiveMinutes,LightlyActiveMinutes,SedentaryMinutes,Calories
0,1503960366,12/04/2016,13162,8.5,8.5,0.0,1.9,0.6,6.1,0.0,25,13,328,728,1985
1,1503960366,13/04/2016,10735,7.0,7.0,0.0,1.6,0.7,4.7,0.0,21,19,217,776,1797
2,1503960366,14/04/2016,10460,6.7,6.7,0.0,2.4,0.4,3.9,0.0,30,11,181,1218,1776
3,1503960366,15/04/2016,9762,6.3,6.3,0.0,2.1,1.3,2.8,0.0,29,34,209,726,1745
4,1503960366,16/04/2016,12669,8.2,8.2,0.0,2.7,0.4,5.0,0.0,36,10,221,773,1863

In [47]:
# check dataset information

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 940 entries, 0 to 939
Data columns (total 15 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Id                        940 non-null    int64
 1   ActivityDate              940 non-null    object
 2   TotalSteps                940 non-null    int64
 3   TotalDistance             940 non-null    float64
 4   TrackerDistance           940 non-null    float64
 5   LoggedActivitiesDistance  940 non-null    float64
 6   VeryActiveDistance        940 non-null    float64
 7   ModeratelyActiveDistance  940 non-null    float64
 8   LightActiveDistance       940 non-null    float64
 9   SedentaryActiveDistance   940 non-null    float64
 10  VeryActiveMinutes         940 non-null    int64
 11  FairlyActiveMinutes       940 non-null    int64
 12  LightlyActiveMinutes      940 non-null    int64
 13  SedentaryMinutes          940 non-null    int64
 14  Calories                  940 non-null    int64
dtypes: float64(7), int64(7), object(1)
memory usage: 110.3+ KB

In [48]:
# shape

df.shape

(940, 15)

In [49]:
# data types

df.dtypes

Id                            int64
ActivityDate                 object
TotalSteps                    int64
TotalDistance               float64
TrackerDistance             float64
LoggedActivitiesDistance    float64
VeryActiveDistance          float64
ModeratelyActiveDistance    float64
LightActiveDistance         float64
SedentaryActiveDistance     float64
VeryActiveMinutes             int64
FairlyActiveMinutes           int64
LightlyActiveMinutes          int64
SedentaryMinutes              int64
Calories                      int64
dtype: object

In [50]:
# Statistics of dataset

df.describe()

,Id,TotalSteps,TotalDistance,TrackerDistance,LoggedActivitiesDistance,VeryActiveDistance,ModeratelyActiveDistance,LightActiveDistance,SedentaryActiveDistance,VeryActiveMinutes,FairlyActiveMinutes,LightlyActiveMinutes,SedentaryMinutes,Calories
count,9.400000e+02,940.000000,940.000000,940.000000,940.000000,940.000000,940.000000,940.000000,940.000000,940.000000,940.000000,940.000000,940.000000,940.000000
mean,4.855407e+09,7637.910638,5.489787,5.475532,0.108723,1.504149,0.567979,3.343191,0.001606,21.164894,13.564894,192.812766,991.210638,2303.609574
std,2.424805e+09,5087.150742,3.923801,3.906519,0.622038,2.658499,0.882432,2.041061,0.007346,32.844803,19.987404,109.174700,301.267437,718.166862
min,1.503960e+09,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,2.320127e+09,3789.750000,2.600000,2.600000,0.000000,0.000000,0.000000,1.975000,0.000000,0.000000,0.000000,127.000000,729.750000,1828.500000
50%,4.445115e+09,7405.500000,5.250000,5.250000,0.000000,0.200000,0.200000,3.400000,0.000000,4.000000,6.000000,199.000000,1057.500000,2134.000000
75%,6.962181e+09,10727.000000,7.700000,7.700000,0.000000,2.025000,0.800000,4.800000,0.000000,32.000000,19.000000,264.000000,1229.500000,2793.250000
max,8.877689e+09,36019.000000,28.000000,28.000000,4.900000,21.900000,6.500000,10.700000,0.110000,210.000000,143.000000,518.000000,1440.000000,4900.000000

In [51]:
# Check missing values

df.isnull().sum()

Id                          0
ActivityDate                0
TotalSteps                  0
TotalDistance               0
TrackerDistance             0
LoggedActivitiesDistance    0
VeryActiveDistance          0
ModeratelyActiveDistance    0
LightActiveDistance         0
SedentaryActiveDistance     0
VeryActiveMinutes           0
FairlyActiveMinutes         0
LightlyActiveMinutes        0
SedentaryMinutes            0
Calories                    0
dtype: int64

In [52]:
# check duplicate records

df.duplicated().sum()

0

### Note: No duplicates and no mising values

In [53]:
df['ActivityDate'] # Need to change the format

0      04/12/2016
1       4/13/2016
2       4/14/2016
3       4/15/2016
4       4/16/2016
          ...
935    05/08/2016
936    05/09/2016
937    05/10/2016
938    05/11/2016
939    05/12/2016
Name: ActivityDate, Length: 940, dtype: object

In [54]:
df['ActivityDate'] = pd.to_datetime(df['ActivityDate'], errors='coerce')

df['ActivityDate'] = df['ActivityDate'].dt.strftime('%d/%m/%Y')

In [55]:
df['ActivityDate']

0      12/04/2016
1      13/04/2016
2      14/04/2016
3      15/04/2016
4      16/04/2016
          ...
935    08/05/2016
936    09/05/2016
937    10/05/2016
938    11/05/2016
939    12/05/2016
Name: ActivityDate, Length: 940, dtype: object

In [56]:
print(df)

             Id ActivityDate  TotalSteps  TotalDistance  TrackerDistance  \
0    1503960366   12/04/2016       13162            8.5              8.5
1    1503960366   13/04/2016       10735            7.0              7.0
2    1503960366   14/04/2016       10460            6.7              6.7
3    1503960366   15/04/2016        9762            6.3              6.3
4    1503960366   16/04/2016       12669            8.2              8.2
..          ...          ...         ...            ...              ...
935  8877689391   08/05/2016       10686            8.1              8.1
936  8877689391   09/05/2016       20226           18.3             18.3
937  8877689391   10/05/2016       10733            8.1              8.1
938  8877689391   11/05/2016       21420           19.6             19.6
939  8877689391   12/05/2016        8064            6.1              6.1

     LoggedActivitiesDistance  VeryActiveDistance  ModeratelyActiveDistance  \
0                         0.0                 1.9                       0.6
1                         0.0                 1.6                       0.7
2                         0.0                 2.4                       0.4
3                         0.0                 2.1                       1.3
4                         0.0                 2.7                       0.4
..                        ...                 ...                       ...
935                       0.0                 1.1                       0.2
936                       0.0                11.1                       0.8
937                       0.0                 1.4                       0.5
938                       0.0                13.2                       0.4
939                       0.0                 1.8                       0.0

     LightActiveDistance  SedentaryActiveDistance  VeryActiveMinutes  \
0                    6.1                     0.00                 25
1                    4.7                     0.00                 21
2                    3.9                     0.00                 30
3                    2.8                     0.00                 29
4                    5.0                     0.00                 36
..                   ...                      ...                ...
935                  6.8                     0.00                 17
936                  6.2                     0.05                 73
937                  6.3                     0.00                 18
938                  5.9                     0.00                 88
939                  4.3                     0.00                 23

     FairlyActiveMinutes  LightlyActiveMinutes  SedentaryMinutes  Calories
0                     13                   328               728      1985
1                     19                   217               776      1797
2                     11                   181              1218      1776
3                     34                   209               726      1745
4                     10                   221               773      1863
..                   ...                   ...               ...       ...
935                    4                   245              1174      2847
936                   19                   217              1131      3710
937                   11                   224              1187      2832
938                   12                   213              1127      3832
939                    1                   137               770      1849

[940 rows x 15 columns]

Converted the ActivityDate column from mixed date formats into a consistent day/month/year format using pandas datetime functions and saved the cleaned dataset for further analysis.

# Save the cleaned dataset

In [57]:
df.to_csv("clean_dailyActivity.csv", index=False)

# Load the cleaned dataset

In [58]:
df = pd.read_csv("clean_dailyActivity.csv")

In [59]:
print(df.head())

           Id ActivityDate  TotalSteps  TotalDistance  TrackerDistance  \
0  1503960366   12/04/2016       13162            8.5              8.5
1  1503960366   13/04/2016       10735            7.0              7.0
2  1503960366   14/04/2016       10460            6.7              6.7
3  1503960366   15/04/2016        9762            6.3              6.3
4  1503960366   16/04/2016       12669            8.2              8.2

   LoggedActivitiesDistance  VeryActiveDistance  ModeratelyActiveDistance  \
0                       0.0                 1.9                       0.6
1                       0.0                 1.6                       0.7
2                       0.0                 2.4                       0.4
3                       0.0                 2.1                       1.3
4                       0.0                 2.7                       0.4

   LightActiveDistance  SedentaryActiveDistance  VeryActiveMinutes  \
0                  6.1                      0.0                 25
1                  4.7                      0.0                 21
2                  3.9                      0.0                 30
3                  2.8                      0.0                 29
4                  5.0                      0.0                 36

   FairlyActiveMinutes  LightlyActiveMinutes  SedentaryMinutes  Calories
0                   13                   328               728      1985
1                   19                   217               776      1797
2                   11                   181              1218      1776
3                   34                   209               726      1745
4                   10                   221               773      1863