In [1]:
# Importing libraries

import pandas as pd
import numpy as np

In [2]:
# Load the dataset

df = pd.read_csv("dailySteps_merged.csv")

In [20]:
print(df)

             Id ActivityDay  StepTotal
0    1503960366  04/12/2016      13162
1    1503960366  13/04/2016      10735
2    1503960366  14/04/2016      10460
3    1503960366  15/04/2016       9762
4    1503960366  16/04/2016      12669
..          ...         ...        ...
935  8877689391  05/08/2016      10686
936  8877689391  05/09/2016      20226
937  8877689391  05/10/2016      10733
938  8877689391  05/11/2016      21420
939  8877689391  05/12/2016       8064

[940 rows x 3 columns]

### Preview the data

In [4]:
df.head()

           Id ActivityDay  StepTotal
0  1503960366  04/12/2016      13162
1  1503960366   4/13/2016      10735
2  1503960366   4/14/2016      10460
3  1503960366   4/15/2016       9762
4  1503960366   4/16/2016      12669

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 940 entries, 0 to 939
Data columns (total 3 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Id           940 non-null    int64
 1   ActivityDay  940 non-null    object
 2   StepTotal    940 non-null    int64
dtypes: int64(2), object(1)
memory usage: 22.2+ KB

In [6]:
# shape

df.shape

(940, 3)

In [7]:
# data types

df.dtypes

Id              int64
ActivityDay    object
StepTotal       int64
dtype: object

In [8]:
# Statistics of dataset

df.describe()

                 Id     StepTotal
count  9.400000e+02    940.000000
mean   4.855407e+09   7637.910638
std    2.424805e+09   5087.150742
min    1.503960e+09      0.000000
25%    2.320127e+09   3789.750000
50%    4.445115e+09   7405.500000
75%    6.962181e+09  10727.000000
max    8.877689e+09  36019.000000

In [9]:
# Check missing values

df.isnull().sum()

Id             0
ActivityDay    0
StepTotal      0
dtype: int64

In [10]:
# check duplicate records

df.duplicated().sum()

0

### Note: No duplicates and no missing values

In [12]:
df["ActivityDay"] # Need to change the format

0      04/12/2016
1       4/13/2016
2       4/14/2016
3       4/15/2016
4       4/16/2016
          ...
935    05/08/2016
936    05/09/2016
937    05/10/2016
938    05/11/2016
939    05/12/2016
Name: ActivityDay, Length: 940, dtype: object

In [13]:
df['ActivityDay'] = pd.to_datetime(df['ActivityDay'], format='mixed', dayfirst=True)

df['ActivityDay'] = df['ActivityDay'].dt.strftime('%d/%m/%Y')

In [14]:
df['ActivityDay']

0      04/12/2016
1      13/04/2016
2      14/04/2016
3      15/04/2016
4      16/04/2016
          ...
935    05/08/2016
936    05/09/2016
937    05/10/2016
938    05/11/2016
939    05/12/2016
Name: ActivityDay, Length: 940, dtype: object

# Save the clean dataset

In [16]:
df.to_csv("clean_dailySteps.csv", index=False)

# Load the clean dataset

In [17]:
df = pd.read_csv("clean_dailySteps.csv")

In [19]:
print(df.head())

           Id ActivityDay  StepTotal
0  1503960366  04/12/2016      13162
1  1503960366  13/04/2016      10735
2  1503960366  14/04/2016      10460
3  1503960366  15/04/2016       9762
4  1503960366  16/04/2016      12669

Cleaned the dailySteps dataset by checking missing values, removing duplicates, and standardizing the ActivityDay column into day/month/year format.