In [106]:
# Importing libraries
import pandas as pd
import numpy as np

In [107]:
# Load the dataset

df = pd.read_csv("dailyIntensities_merged.csv")

In [108]:
df

,Id,ActivityDay,SedentaryMinutes,LightlyActiveMinutes,FairlyActiveMinutes,VeryActiveMinutes,SedentaryActiveDistance,LightActiveDistance,ModeratelyActiveDistance,VeryActiveDistance
0,1503960366,04-12-2016,728,328,13,25,0.00,6.1,0.6,1.9
1,1503960366,4/13/2016,776,217,19,21,0.00,4.7,0.7,1.6
2,1503960366,4/14/2016,1218,181,11,30,0.00,3.9,0.4,2.4
3,1503960366,4/15/2016,726,209,34,29,0.00,2.8,1.3,2.1
4,1503960366,4/16/2016,773,221,10,36,0.00,5.0,0.4,2.7
...,...,...,...,...,...,...,...,...,...,...
935,8877689391,05-08-2016,1174,245,4,17,0.00,6.8,0.2,1.1
936,8877689391,05-09-2016,1131,217,19,73,0.05,6.2,0.8,11.1
937,8877689391,05-10-2016,1187,224,11,18,0.00,6.3,0.5,1.4
938,8877689391,05-11-2016,1127,213,12,88,0.00,5.9,0.4,13.2
939,8877689391,05-12-2016,770,137,1,23,0.00,4.3,0.0,1.8

### Quick Overview

In [109]:
# Display first few rows
df.head()

,Id,ActivityDay,SedentaryMinutes,LightlyActiveMinutes,FairlyActiveMinutes,VeryActiveMinutes,SedentaryActiveDistance,LightActiveDistance,ModeratelyActiveDistance,VeryActiveDistance
0,1503960366,04-12-2016,728,328,13,25,0.0,6.1,0.6,1.9
1,1503960366,4/13/2016,776,217,19,21,0.0,4.7,0.7,1.6
2,1503960366,4/14/2016,1218,181,11,30,0.0,3.9,0.4,2.4
3,1503960366,4/15/2016,726,209,34,29,0.0,2.8,1.3,2.1
4,1503960366,4/16/2016,773,221,10,36,0.0,5.0,0.4,2.7

In [110]:
# check dataset information

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 940 entries, 0 to 939
Data columns (total 10 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Id                        940 non-null    int64
 1   ActivityDay               940 non-null    object
 2   SedentaryMinutes          940 non-null    int64
 3   LightlyActiveMinutes      940 non-null    int64
 4   FairlyActiveMinutes       940 non-null    int64
 5   VeryActiveMinutes         940 non-null    int64
 6   SedentaryActiveDistance   940 non-null    float64
 7   LightActiveDistance       940 non-null    float64
 8   ModeratelyActiveDistance  940 non-null    float64
 9   VeryActiveDistance        940 non-null    float64
dtypes: float64(4), int64(5), object(1)
memory usage: 73.6+ KB

In [111]:
# shape

df.shape

(940, 10)

In [112]:
# data types

df.dtypes

Id                            int64
ActivityDay                  object
SedentaryMinutes              int64
LightlyActiveMinutes          int64
FairlyActiveMinutes           int64
VeryActiveMinutes             int64
SedentaryActiveDistance     float64
LightActiveDistance         float64
ModeratelyActiveDistance    float64
VeryActiveDistance          float64
dtype: object

In [113]:
# Statistics of dataset

df.describe()

,Id,SedentaryMinutes,LightlyActiveMinutes,FairlyActiveMinutes,VeryActiveMinutes,SedentaryActiveDistance,LightActiveDistance,ModeratelyActiveDistance,VeryActiveDistance
count,9.400000e+02,940.000000,940.000000,940.000000,940.000000,940.000000,940.000000,940.000000,940.000000
mean,4.855407e+09,991.210638,192.812766,13.564894,21.164894,0.001606,3.343191,0.567979,1.504149
std,2.424805e+09,301.267437,109.174700,19.987404,32.844803,0.007346,2.041061,0.882432,2.658499
min,1.503960e+09,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,2.320127e+09,729.750000,127.000000,0.000000,0.000000,0.000000,1.975000,0.000000,0.000000
50%,4.445115e+09,1057.500000,199.000000,6.000000,4.000000,0.000000,3.400000,0.200000,0.200000
75%,6.962181e+09,1229.500000,264.000000,19.000000,32.000000,0.000000,4.800000,0.800000,2.025000
max,8.877689e+09,1440.000000,518.000000,143.000000,210.000000,0.110000,10.700000,6.500000,21.900000

In [114]:
# Check missing values

df.isnull().sum()

Id                          0
ActivityDay                 0
SedentaryMinutes            0
LightlyActiveMinutes        0
FairlyActiveMinutes         0
VeryActiveMinutes           0
SedentaryActiveDistance     0
LightActiveDistance         0
ModeratelyActiveDistance    0
VeryActiveDistance          0
dtype: int64

In [115]:
# check duplicate records

df.duplicated().sum()

0

# Note: No duplicates and no missing values

In [116]:
df['ActivityDay'] # Need to change the format

0      04-12-2016
1       4/13/2016
2       4/14/2016
3       4/15/2016
4       4/16/2016
          ...
935    05-08-2016
936    05-09-2016
937    05-10-2016
938    05-11-2016
939    05-12-2016
Name: ActivityDay, Length: 940, dtype: object

In [117]:
df['ActivityDay'] = pd.to_datetime(df['ActivityDay'], format='mixed', dayfirst=True)

df['ActivityDay'] = df['ActivityDay'].dt.strftime('%d/%m/%Y')

In [118]:
df['ActivityDay'].isnull().sum()

0

In [119]:
df.isnull().sum()

Id                          0
ActivityDay                 0
SedentaryMinutes            0
LightlyActiveMinutes        0
FairlyActiveMinutes         0
VeryActiveMinutes           0
SedentaryActiveDistance     0
LightActiveDistance         0
ModeratelyActiveDistance    0
VeryActiveDistance          0
dtype: int64

In [120]:
df['ActivityDay']

0      04/12/2016
1      13/04/2016
2      14/04/2016
3      15/04/2016
4      16/04/2016
          ...
935    05/08/2016
936    05/09/2016
937    05/10/2016
938    05/11/2016
939    05/12/2016
Name: ActivityDay, Length: 940, dtype: object

In [121]:
df['ActivityDay'].isnull().sum()

0

# Save the clean dataset

In [122]:
df.to_csv("clean_dailyIntensities.csv", index=False)

# Loading the clean dataset

In [123]:
df = pd.read_csv("clean_dailyIntensities.csv")

In [125]:
df.head()

,Id,ActivityDay,SedentaryMinutes,LightlyActiveMinutes,FairlyActiveMinutes,VeryActiveMinutes,SedentaryActiveDistance,LightActiveDistance,ModeratelyActiveDistance,VeryActiveDistance
0,1503960366,04/12/2016,728,328,13,25,0.0,6.1,0.6,1.9
1,1503960366,13/04/2016,776,217,19,21,0.0,4.7,0.7,1.6
2,1503960366,14/04/2016,1218,181,11,30,0.0,3.9,0.4,2.4
3,1503960366,15/04/2016,726,209,34,29,0.0,2.8,1.3,2.1
4,1503960366,16/04/2016,773,221,10,36,0.0,5.0,0.4,2.7

In [126]:
df

,Id,ActivityDay,SedentaryMinutes,LightlyActiveMinutes,FairlyActiveMinutes,VeryActiveMinutes,SedentaryActiveDistance,LightActiveDistance,ModeratelyActiveDistance,VeryActiveDistance
0,1503960366,04/12/2016,728,328,13,25,0.00,6.1,0.6,1.9
1,1503960366,13/04/2016,776,217,19,21,0.00,4.7,0.7,1.6
2,1503960366,14/04/2016,1218,181,11,30,0.00,3.9,0.4,2.4
3,1503960366,15/04/2016,726,209,34,29,0.00,2.8,1.3,2.1
4,1503960366,16/04/2016,773,221,10,36,0.00,5.0,0.4,2.7
...,...,...,...,...,...,...,...,...,...,...
935,8877689391,05/08/2016,1174,245,4,17,0.00,6.8,0.2,1.1
936,8877689391,05/09/2016,1131,217,19,73,0.05,6.2,0.8,11.1
937,8877689391,05/10/2016,1187,224,11,18,0.00,6.3,0.5,1.4
938,8877689391,05/11/2016,1127,213,12,88,0.00,5.9,0.4,13.2
939,8877689391,05/12/2016,770,137,1,23,0.00,4.3,0.0,1.8