In [35]:
import pandas as pd

In [36]:
df = pd.read_csv("sleepDay_merged.csv")

In [37]:
df.head()

,Id,SleepDay,TotalSleepRecords,TotalMinutesAsleep,TotalTimeInBed
0,1503960366,04/12/2016 12:00:00 AM,1,327,346
1,1503960366,4/13/2016 12:00:00 AM,2,384,407
2,1503960366,4/15/2016 12:00:00 AM,1,412,442
3,1503960366,4/16/2016 12:00:00 AM,2,340,367
4,1503960366,4/17/2016 12:00:00 AM,1,700,712

# Quick Overview

In [38]:
# few rows

df.head()

,Id,SleepDay,TotalSleepRecords,TotalMinutesAsleep,TotalTimeInBed
0,1503960366,04/12/2016 12:00:00 AM,1,327,346
1,1503960366,4/13/2016 12:00:00 AM,2,384,407
2,1503960366,4/15/2016 12:00:00 AM,1,412,442
3,1503960366,4/16/2016 12:00:00 AM,2,340,367
4,1503960366,4/17/2016 12:00:00 AM,1,700,712

In [39]:
# Dataset info

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 413 entries, 0 to 412
Data columns (total 5 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Id                  413 non-null    int64
 1   SleepDay            413 non-null    object
 2   TotalSleepRecords   413 non-null    int64
 3   TotalMinutesAsleep  413 non-null    int64
 4   TotalTimeInBed      413 non-null    int64
dtypes: int64(4), object(1)
memory usage: 16.3+ KB

In [40]:
# datatypes of the dataset

df.dtypes

Id                     int64
SleepDay              object
TotalSleepRecords      int64
TotalMinutesAsleep     int64
TotalTimeInBed         int64
dtype: object

#### In this dataset, we mostly have numeric data

In [41]:
# Check missing values

df.isnull().sum()

Id                    0
SleepDay              0
TotalSleepRecords     0
TotalMinutesAsleep    0
TotalTimeInBed        0
dtype: int64

In [42]:
# check duplicate records

df.duplicated().sum()

3

In [43]:
# Remove duplicates

df = df.drop_duplicates()

In [44]:
# check duplicate records again

df.duplicated().sum()

0

In [45]:
df["SleepDay"] # Need to convert the column into date

0      04/12/2016 12:00:00  AM
1        4/13/2016 12:00:00 AM
2        4/15/2016 12:00:00 AM
3        4/16/2016 12:00:00 AM
4        4/17/2016 12:00:00 AM
                ...
408      4/30/2016 12:00:00 AM
409    05/01/2016 12:00:00  AM
410    05/02/2016 12:00:00  AM
411    05/03/2016 12:00:00  AM
412    05/04/2016 12:00:00  AM
Name: SleepDay, Length: 410, dtype: object

### Convert to dd/mm/yyyy

In [46]:
df['SleepDay'] = pd.to_datetime(df['SleepDay'], format='mixed')

In [47]:
df['SleepDay']

0     2016-04-12
1     2016-04-13
2     2016-04-15
3     2016-04-16
4     2016-04-17
         ...
408   2016-04-30
409   2016-05-01
410   2016-05-02
411   2016-05-03
412   2016-05-04
Name: SleepDay, Length: 410, dtype: datetime64[ns]

### Convert to dd/mm/yyyy

In [48]:
df['SleepDay'] = df['SleepDay'].dt.strftime('%d/%m/%Y')

### Verify

In [49]:
df['SleepDay'].head()

0    12/04/2016
1    13/04/2016
2    15/04/2016
3    16/04/2016
4    17/04/2016
Name: SleepDay, dtype: object

# Saving clean dataset

In [50]:
df.to_csv("clean_sleepDay.csv", index = False)

# Loading the clean dataset

In [51]:
df = pd.read_csv("clean_sleepDay.csv")

In [52]:
df.head()

,Id,SleepDay,TotalSleepRecords,TotalMinutesAsleep,TotalTimeInBed
0,1503960366,12/04/2016,1,327,346
1,1503960366,13/04/2016,2,384,407
2,1503960366,15/04/2016,1,412,442
3,1503960366,16/04/2016,2,340,367
4,1503960366,17/04/2016,1,700,712

Dataset is now successfully clean removing duplicate records and converting the SleepDay column from datetime format into a standardized day/month/year format.