In [1]:
# Importing libraries
import pandas as pd
import numpy as np

In [2]:
# Load the dataset

df = pd.read_csv("dailyCalories_merged.csv")

In [3]:
df

             Id ActivityDay  Calories
0    1503960366  04/12/2016      1985
1    1503960366   4/13/2016      1797
2    1503960366   4/14/2016      1776
3    1503960366   4/15/2016      1745
4    1503960366   4/16/2016      1863
..          ...         ...       ...
935  8877689391  05/08/2016      2847
936  8877689391  05/09/2016      3710
937  8877689391  05/10/2016      2832
938  8877689391  05/11/2016      3832
939  8877689391  05/12/2016      1849

[940 rows x 3 columns]

### Quick Overview

In [4]:
# Display first few rows
df.head()

           Id ActivityDay  Calories
0  1503960366  04/12/2016      1985
1  1503960366   4/13/2016      1797
2  1503960366   4/14/2016      1776
3  1503960366   4/15/2016      1745
4  1503960366   4/16/2016      1863

In [5]:
# check dataset information

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 940 entries, 0 to 939
Data columns (total 3 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Id           940 non-null    int64
 1   ActivityDay  940 non-null    object
 2   Calories     940 non-null    int64
dtypes: int64(2), object(1)
memory usage: 22.2+ KB

In [6]:
# shape

df.shape

(940, 3)

In [7]:
# data types

df.dtypes

Id              int64
ActivityDay    object
Calories        int64
dtype: object

In [8]:
# Statistics of dataset

df.describe()

                 Id     Calories
count  9.400000e+02   940.000000
mean   4.855407e+09  2303.609574
std    2.424805e+09   718.166862
min    1.503960e+09     0.000000
25%    2.320127e+09  1828.500000
50%    4.445115e+09  2134.000000
75%    6.962181e+09  2793.250000
max    8.877689e+09  4900.000000

In [9]:
# Check missing values

df.isnull().sum()

Id             0
ActivityDay    0
Calories       0
dtype: int64

In [10]:
# check duplicate records

df.duplicated().sum()

0

### Note: No duplicates and no mising values

In [12]:
df['ActivityDay'] # Need to change the format

0      04/12/2016
1       4/13/2016
2       4/14/2016
3       4/15/2016
4       4/16/2016
          ...
935    05/08/2016
936    05/09/2016
937    05/10/2016
938    05/11/2016
939    05/12/2016
Name: ActivityDay, Length: 940, dtype: object

In [13]:
df['ActivityDay'] = pd.to_datetime(df['ActivityDay'], errors='coerce')

df['ActivityDay'] = df['ActivityDay'].dt.strftime('%d/%m/%Y')

In [14]:
df['ActivityDay']

0      12/04/2016
1      13/04/2016
2      14/04/2016
3      15/04/2016
4      16/04/2016
          ...
935    08/05/2016
936    09/05/2016
937    10/05/2016
938    11/05/2016
939    12/05/2016
Name: ActivityDay, Length: 940, dtype: object

In [15]:
print(df)

             Id ActivityDay  Calories
0    1503960366  12/04/2016      1985
1    1503960366  13/04/2016      1797
2    1503960366  14/04/2016      1776
3    1503960366  15/04/2016      1745
4    1503960366  16/04/2016      1863
..          ...         ...       ...
935  8877689391  08/05/2016      2847
936  8877689391  09/05/2016      3710
937  8877689391  10/05/2016      2832
938  8877689391  11/05/2016      3832
939  8877689391  12/05/2016      1849

[940 rows x 3 columns]

Converted mixed date formats into a consistent day/month/year format.

# Save Clean Dataset

In [16]:
df.to_csv("clean_dailyCalories.csv", index=False)

# Load Clean Dataset

In [17]:
df = pd.read_csv("clean_dailyCalories.csv")

In [18]:
print(df.head())

           Id ActivityDay  Calories
0  1503960366  12/04/2016      1985
1  1503960366  13/04/2016      1797
2  1503960366  14/04/2016      1776
3  1503960366  15/04/2016      1745
4  1503960366  16/04/2016      1863