### EDA stands for Exploratory Data Analysis which means  understanding the data before building insights or dashboards.

Merging below datasets as they all contain id and daily activity data

1. clean_dailyActivity.csv

2. clean_dailyCalories.csv

3. clean_dailyIntensities.csv

4. clean_dailySteps.csv

In [1]:
import pandas as pd

## Standardize the date column in all datasets

In [4]:
import pandas as pd

# Load datasets
activity = pd.read_csv("clean_dailyActivity.csv")
calories = pd.read_csv("clean_dailyCalories.csv")
intensity = pd.read_csv("clean_dailyIntensities.csv")
steps = pd.read_csv("clean_dailySteps.csv")

# Standardize the date column name in all datasets
activity.rename(columns={'ActivityDate':'ActivityDay'}, inplace=True)
calories.rename(columns={'ActivityDay':'ActivityDay'}, inplace=True)
intensity.rename(columns={'ActivityDay':'ActivityDay'}, inplace=True)
steps.rename(columns={'ActivityDay':'ActivityDay'}, inplace=True)

## Merge Daily Datasets

In [6]:
daily_master = activity.merge(calories, on=['Id','ActivityDay'], how='inner') \
                       .merge(intensity, on=['Id','ActivityDay'], how='inner') \
                       .merge(steps, on=['Id','ActivityDay'], how='inner')

In [11]:
# Check the merged dataset
print(daily_master.shape)

(607, 25)

In [12]:
daily_master.head()

,Id,ActivityDay,TotalSteps,TotalDistance,TrackerDistance,LoggedActivitiesDistance,VeryActiveDistance_x,ModeratelyActiveDistance_x,LightActiveDistance_x,SedentaryActiveDistance_x,...,Calories_y,SedentaryMinutes_y,LightlyActiveMinutes_y,FairlyActiveMinutes_y,VeryActiveMinutes_y,SedentaryActiveDistance_y,LightActiveDistance_y,ModeratelyActiveDistance_y,VeryActiveDistance_y,StepTotal
0,1503960366,13/04/2016,10735,7.0,7.0,0.0,1.6,0.7,4.7,0.0,...,1797,776,217,19,21,0.0,4.7,0.7,1.6,10735
1,1503960366,14/04/2016,10460,6.7,6.7,0.0,2.4,0.4,3.9,0.0,...,1776,1218,181,11,30,0.0,3.9,0.4,2.4,10460
2,1503960366,15/04/2016,9762,6.3,6.3,0.0,2.1,1.3,2.8,0.0,...,1745,726,209,34,29,0.0,2.8,1.3,2.1,9762
3,1503960366,16/04/2016,12669,8.2,8.2,0.0,2.7,0.4,5.0,0.0,...,1863,773,221,10,36,0.0,5.0,0.4,2.7,12669
4,1503960366,17/04/2016,9705,6.5,6.5,0.0,3.2,0.8,2.5,0.0,...,1728,539,164,20,38,0.0,2.5,0.8,3.2,9705

In [13]:
daily_master

,Id,ActivityDay,TotalSteps,TotalDistance,TrackerDistance,LoggedActivitiesDistance,VeryActiveDistance_x,ModeratelyActiveDistance_x,LightActiveDistance_x,SedentaryActiveDistance_x,...,Calories_y,SedentaryMinutes_y,LightlyActiveMinutes_y,FairlyActiveMinutes_y,VeryActiveMinutes_y,SedentaryActiveDistance_y,LightActiveDistance_y,ModeratelyActiveDistance_y,VeryActiveDistance_y,StepTotal
0,1503960366,13/04/2016,10735,7.0,7.0,0.0,1.6,0.7,4.7,0.0,...,1797,776,217,19,21,0.0,4.7,0.7,1.6,10735
1,1503960366,14/04/2016,10460,6.7,6.7,0.0,2.4,0.4,3.9,0.0,...,1776,1218,181,11,30,0.0,3.9,0.4,2.4,10460
2,1503960366,15/04/2016,9762,6.3,6.3,0.0,2.1,1.3,2.8,0.0,...,1745,726,209,34,29,0.0,2.8,1.3,2.1,9762
3,1503960366,16/04/2016,12669,8.2,8.2,0.0,2.7,0.4,5.0,0.0,...,1863,773,221,10,36,0.0,5.0,0.4,2.7,12669
4,1503960366,17/04/2016,9705,6.5,6.5,0.0,3.2,0.8,2.5,0.0,...,1728,539,164,20,38,0.0,2.5,0.8,3.2,9705
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
602,8877689391,27/04/2016,23629,20.6,20.6,0.0,13.1,0.4,7.1,0.0,...,3808,1104,235,8,93,0.0,7.1,0.4,13.1,23629
603,8877689391,28/04/2016,14890,11.3,11.3,0.0,4.9,0.4,6.0,0.0,...,3060,1143,231,8,58,0.0,6.0,0.4,4.9,14890
604,8877689391,29/04/2016,9733,7.4,7.4,0.0,1.4,0.2,5.8,0.0,...,2698,1207,210,5,18,0.0,5.8,0.2,1.4,9733
605,8877689391,30/04/2016,27745,26.7,26.7,0.0,21.7,0.1,4.9,0.0,...,4398,1089,223,4,124,0.0,4.9,0.1,21.7,27745
606,8877689391,05/05/2016,14055,10.7,10.7,0.0,5.5,0.8,4.4,0.0,...,3052,1170,188,15,67,0.0,4.4,0.8,5.5,14055

# Save the Merge Dataset

In [17]:
daily_master.to_csv("Merge_daily_activity_master.csv", index=False)

# Load the merge dataset

In [18]:
df = pd.read_csv("Merge_daily_activity_master.csv")

In [19]:
df.head()

,Id,ActivityDay,TotalSteps,TotalDistance,TrackerDistance,LoggedActivitiesDistance,VeryActiveDistance_x,ModeratelyActiveDistance_x,LightActiveDistance_x,SedentaryActiveDistance_x,...,Calories_y,SedentaryMinutes_y,LightlyActiveMinutes_y,FairlyActiveMinutes_y,VeryActiveMinutes_y,SedentaryActiveDistance_y,LightActiveDistance_y,ModeratelyActiveDistance_y,VeryActiveDistance_y,StepTotal
0,1503960366,13/04/2016,10735,7.0,7.0,0.0,1.6,0.7,4.7,0.0,...,1797,776,217,19,21,0.0,4.7,0.7,1.6,10735
1,1503960366,14/04/2016,10460,6.7,6.7,0.0,2.4,0.4,3.9,0.0,...,1776,1218,181,11,30,0.0,3.9,0.4,2.4,10460
2,1503960366,15/04/2016,9762,6.3,6.3,0.0,2.1,1.3,2.8,0.0,...,1745,726,209,34,29,0.0,2.8,1.3,2.1,9762
3,1503960366,16/04/2016,12669,8.2,8.2,0.0,2.7,0.4,5.0,0.0,...,1863,773,221,10,36,0.0,5.0,0.4,2.7,12669
4,1503960366,17/04/2016,9705,6.5,6.5,0.0,3.2,0.8,2.5,0.0,...,1728,539,164,20,38,0.0,2.5,0.8,3.2,9705