In [1]:
import pandas as pd

In [2]:
df1 = pd.read_csv("Merge_daily_activity_master.csv")

In [4]:
df2 = pd.read_csv("clean_weightLogInfo.csv")

In [11]:
df = pd.merge(df1, df2, 
                           left_on=['Id','ActivityDay'], 
                           right_on=['Id','Date'],
                           how='inner')

In [12]:
df.head()

,Id,ActivityDay,TotalSteps,TotalDistance,TrackerDistance,LoggedActivitiesDistance,VeryActiveDistance_x,ModeratelyActiveDistance_x,LightActiveDistance_x,SedentaryActiveDistance_x,...,ModeratelyActiveDistance_y,VeryActiveDistance_y,StepTotal,Date,WeightKg,WeightPounds,Fat,BMI,IsManualReport,LogId
0,1927972279,13/04/2016,356,0.3,0.3,0.0,0.0,0.0,0.3,0.00,...,0.0,0.0,356,13/04/2016,133.5,294.32,NaN,47.54,False,1.460510e+12
1,2873212765,21/04/2016,8859,6.0,6.0,0.0,0.1,0.4,5.5,0.01,...,0.4,0.1,8859,21/04/2016,56.7,125.00,NaN,21.45,True,1.461280e+12
2,4319703577,17/04/2016,29,0.0,0.0,0.0,0.0,0.0,0.0,0.00,...,0.0,0.0,29,17/04/2016,72.4,159.61,25.0,27.45,True,1.460940e+12
3,4558609924,18/04/2016,8940,5.9,5.9,0.0,1.0,0.9,4.0,0.00,...,0.9,1.0,8940,18/04/2016,69.7,153.66,NaN,27.25,True,1.461020e+12
4,4558609924,25/04/2016,8095,5.3,5.3,0.0,0.6,0.3,4.5,0.00,...,0.3,0.6,8095,25/04/2016,70.3,154.98,NaN,27.46,True,1.461630e+12

# Now we can analyze: Steps vs Weight, Calories vs Weight, BMI trends

# save the merge dataset

In [14]:
df.to_csv("Merge_DailyActivity&Weight.csv", index = False)

## Loading the merge file

In [15]:
df = pd.read_csv("Merge_DailyActivity&Weight.csv")

In [16]:
df.head()

,Id,ActivityDay,TotalSteps,TotalDistance,TrackerDistance,LoggedActivitiesDistance,VeryActiveDistance_x,ModeratelyActiveDistance_x,LightActiveDistance_x,SedentaryActiveDistance_x,...,ModeratelyActiveDistance_y,VeryActiveDistance_y,StepTotal,Date,WeightKg,WeightPounds,Fat,BMI,IsManualReport,LogId
0,1927972279,13/04/2016,356,0.3,0.3,0.0,0.0,0.0,0.3,0.00,...,0.0,0.0,356,13/04/2016,133.5,294.32,NaN,47.54,False,1.460510e+12
1,2873212765,21/04/2016,8859,6.0,6.0,0.0,0.1,0.4,5.5,0.01,...,0.4,0.1,8859,21/04/2016,56.7,125.00,NaN,21.45,True,1.461280e+12
2,4319703577,17/04/2016,29,0.0,0.0,0.0,0.0,0.0,0.0,0.00,...,0.0,0.0,29,17/04/2016,72.4,159.61,25.0,27.45,True,1.460940e+12
3,4558609924,18/04/2016,8940,5.9,5.9,0.0,1.0,0.9,4.0,0.00,...,0.9,1.0,8940,18/04/2016,69.7,153.66,NaN,27.25,True,1.461020e+12
4,4558609924,25/04/2016,8095,5.3,5.3,0.0,0.6,0.3,4.5,0.00,...,0.3,0.6,8095,25/04/2016,70.3,154.98,NaN,27.46,True,1.461630e+12

In [18]:
df.shape

(39, 32)