In [46]:
import pandas as pd

In [47]:
df1 = pd.read_csv("Merge_daily_activity_master.csv")

In [48]:
df2 = pd.read_csv("clean_sleepDay.csv")

In [49]:
df = pd.merge(df1, df2, 
                          left_on=['Id','ActivityDay'], 
                          right_on=['Id','SleepDay'],
                          how='inner')

In [50]:
df.head()

,Id,ActivityDay,TotalSteps,TotalDistance,TrackerDistance,LoggedActivitiesDistance,VeryActiveDistance_x,ModeratelyActiveDistance_x,LightActiveDistance_x,SedentaryActiveDistance_x,...,VeryActiveMinutes_y,SedentaryActiveDistance_y,LightActiveDistance_y,ModeratelyActiveDistance_y,VeryActiveDistance_y,StepTotal,SleepDay,TotalSleepRecords,TotalMinutesAsleep,TotalTimeInBed
0,1503960366,13/04/2016,10735,7.0,7.0,0.0,1.6,0.7,4.7,0.0,...,21,0.0,4.7,0.7,1.6,10735,13/04/2016,2,384,407
1,1503960366,15/04/2016,9762,6.3,6.3,0.0,2.1,1.3,2.8,0.0,...,29,0.0,2.8,1.3,2.1,9762,15/04/2016,1,412,442
2,1503960366,16/04/2016,12669,8.2,8.2,0.0,2.7,0.4,5.0,0.0,...,36,0.0,5.0,0.4,2.7,12669,16/04/2016,2,340,367
3,1503960366,17/04/2016,9705,6.5,6.5,0.0,3.2,0.8,2.5,0.0,...,38,0.0,2.5,0.8,3.2,9705,17/04/2016,1,700,712
4,1503960366,19/04/2016,15506,9.9,9.9,0.0,3.5,1.3,5.0,0.0,...,50,0.0,5.0,1.3,3.5,15506,19/04/2016,1,304,320

# Now we can analyze: Steps vs Sleep, Active Minutes vs Sleep

# Save the merge dataset

In [51]:
df.to_csv("Merge_DailyActivity&Sleep.csv", index = False)

# Load the merge file

In [52]:
df = pd.read_csv("Merge_DailyActivity&Sleep.csv")

In [53]:
df.head()

,Id,ActivityDay,TotalSteps,TotalDistance,TrackerDistance,LoggedActivitiesDistance,VeryActiveDistance_x,ModeratelyActiveDistance_x,LightActiveDistance_x,SedentaryActiveDistance_x,...,VeryActiveMinutes_y,SedentaryActiveDistance_y,LightActiveDistance_y,ModeratelyActiveDistance_y,VeryActiveDistance_y,StepTotal,SleepDay,TotalSleepRecords,TotalMinutesAsleep,TotalTimeInBed
0,1503960366,13/04/2016,10735,7.0,7.0,0.0,1.6,0.7,4.7,0.0,...,21,0.0,4.7,0.7,1.6,10735,13/04/2016,2,384,407
1,1503960366,15/04/2016,9762,6.3,6.3,0.0,2.1,1.3,2.8,0.0,...,29,0.0,2.8,1.3,2.1,9762,15/04/2016,1,412,442
2,1503960366,16/04/2016,12669,8.2,8.2,0.0,2.7,0.4,5.0,0.0,...,36,0.0,5.0,0.4,2.7,12669,16/04/2016,2,340,367
3,1503960366,17/04/2016,9705,6.5,6.5,0.0,3.2,0.8,2.5,0.0,...,38,0.0,2.5,0.8,3.2,9705,17/04/2016,1,700,712
4,1503960366,19/04/2016,15506,9.9,9.9,0.0,3.5,1.3,5.0,0.0,...,50,0.0,5.0,1.3,3.5,15506,19/04/2016,1,304,320